### ISSUE TITLE
Feature request: multiple currencies per widget

### ISSUE THREAD

**Issue by jspraul** [nlgtuankiet/cj#2]
Initial feedback from someone else on a Twitch cryptocurrency channel Discord:

>Crypto bubbles is one I use till I can find a better one.  It's not the best iv seen.  But it didn't cost much ... like ... 2$ ?
> Looks good , need to play with it some more....    would like to put more then 1 in a widget....  ... like..  a 5x5 but put maybe 3 or 4 different  crypto in them instead of a 2x1 for each

So if you're thinking about monetization, maybe this feature could be an in-app purchase.

**Comment by nlgtuankiet** [comment]
we have #1 that implements a watchlist widget 
Is this what you are looking for?

<img src="https://user-images.githubusercontent.com/46102107/137665265-3e99f322-1536-4f25-a211-f6d74f80cb82.jpg" width="300" height="auto">

If that is the case then version 1.8.0 is already released and currently being review by google play!
It should be up by tomorrow :D
Can I have a link to Twitch cryptocurrency channel Discord?

**Comment by jspraul** [comment]
Looks Good To Me!

https://www.twitch.tv/doctor_degen -> https://discord.com/invite/decentralizednn
